/* CodeTrack — Predefined Problem Sheets Data */

const SHEETS = {
    leetcode75: {
        name: 'LeetCode 75',
        desc: "LeetCode's official 75-question study plan for interview prep.",
        icon: '🟩',
        problems: [
            [1768, 'Merge Strings Alternately', 'easy', ['Strings', 'Two Pointers']],
            [1071, 'Greatest Common Divisor of Strings', 'easy', ['Strings', 'Math']],
            [1431, 'Kids With the Greatest Number of Candies', 'easy', ['Arrays']],
            [605, 'Can Place Flowers', 'easy', ['Arrays', 'Greedy']],
            [345, 'Reverse Vowels of a String', 'easy', ['Strings', 'Two Pointers']],
            [151, 'Reverse Words in a String', 'medium', ['Strings']],
            [238, 'Product of Array Except Self', 'medium', ['Arrays']],
            [334, 'Increasing Triplet Subsequence', 'medium', ['Arrays', 'Greedy']],
            [443, 'String Compression', 'medium', ['Strings', 'Two Pointers']],
            [283, 'Move Zeroes', 'easy', ['Arrays', 'Two Pointers']],
            [392, 'Is Subsequence', 'easy', ['Strings', 'Two Pointers']],
            [11, 'Container With Most Water', 'medium', ['Arrays', 'Two Pointers']],
            [1679, 'Max Number of K-Sum Pairs', 'medium', ['Arrays', 'Two Pointers', 'Hash Map']],
            [643, 'Maximum Average Subarray I', 'easy', ['Arrays', 'Sliding Window']],
            [1456, 'Maximum Number of Vowels in a Substring', 'medium', ['Strings', 'Sliding Window']],
            [1004, 'Max Consecutive Ones III', 'medium', ['Arrays', 'Sliding Window']],
            [1493, 'Longest Subarray of 1s After Deleting One Element', 'medium', ['Arrays', 'Sliding Window']],
            [1732, 'Find the Highest Altitude', 'easy', ['Arrays', 'Prefix Sum']],
            [724, 'Find Pivot Index', 'easy', ['Arrays', 'Prefix Sum']],
            [2215, 'Find the Difference of Two Arrays', 'easy', ['Arrays', 'Hash Map']],
            [1207, 'Unique Number of Occurrences', 'easy', ['Arrays', 'Hash Map']],
            [1657, 'Determine if Two Strings Are Close', 'medium', ['Strings', 'Hash Map', 'Sorting']],
            [2352, 'Equal Row and Column Pairs', 'medium', ['Arrays', 'Hash Map', 'Matrix']],
            [2390, 'Removing Stars From a String', 'medium', ['Strings', 'Stack']],
            [735, 'Asteroid Collision', 'medium', ['Arrays', 'Stack']],
            [394, 'Decode String', 'medium', ['Strings', 'Stack']],
            [933, 'Number of Recent Calls', 'easy', ['Queue']],
            [649, 'Dota2 Senate', 'medium', ['Strings', 'Queue', 'Greedy']],
            [2095, 'Delete the Middle Node of a Linked List', 'medium', ['Linked List', 'Two Pointers']],
            [328, 'Odd Even Linked List', 'medium', ['Linked List']],
            [206, 'Reverse Linked List', 'easy', ['Linked List']],
            [2130, 'Maximum Twin Sum of a Linked List', 'medium', ['Linked List', 'Two Pointers']],
            [104, 'Maximum Depth of Binary Tree', 'easy', ['Trees', 'DFS', 'BFS']],
            [872, 'Leaf-Similar Trees', 'easy', ['Trees', 'DFS']],
            [1448, 'Count Good Nodes in Binary Tree', 'medium', ['Trees', 'DFS']],
            [437, 'Path Sum III', 'medium', ['Trees', 'DFS', 'Prefix Sum']],
            [1372, 'Longest ZigZag Path in a Binary Tree', 'medium', ['Trees', 'DFS', 'DP']],
            [236, 'Lowest Common Ancestor of a Binary Tree', 'medium', ['Trees', 'DFS']],
            [199, 'Binary Tree Right Side View', 'medium', ['Trees', 'BFS']],
            [1161, 'Maximum Level Sum of a Binary Tree', 'medium', ['Trees', 'BFS']],
            [700, 'Search in a Binary Search Tree', 'easy', ['Trees', 'BST']],
            [450, 'Delete Node in a BST', 'medium', ['Trees', 'BST']],
            [841, 'Keys and Rooms', 'medium', ['Graphs', 'DFS', 'BFS']],
            [547, 'Number of Provinces', 'medium', ['Graphs', 'DFS', 'Union Find']],
            [1466, 'Reorder Routes to Make All Paths Lead to City Zero', 'medium', ['Graphs', 'DFS', 'BFS']],
            [399, 'Evaluate Division', 'medium', ['Graphs', 'DFS', 'BFS', 'Union Find']],
            [1926, 'Nearest Exit from Entrance in Maze', 'medium', ['Graphs', 'BFS', 'Matrix']],
            [994, 'Rotting Oranges', 'medium', ['Graphs', 'BFS', 'Matrix']],
            [215, 'Kth Largest Element in an Array', 'medium', ['Heap', 'Sorting']],
            [2336, 'Smallest Number in Infinite Set', 'medium', ['Heap', 'Hash Map']],
            [2542, 'Maximum Subsequence Score', 'medium', ['Heap', 'Greedy', 'Sorting']],
            [2462, 'Total Cost to Hire K Workers', 'medium', ['Heap']],
            [374, 'Guess Number Higher or Lower', 'easy', ['Binary Search']],
            [2300, 'Successful Pairs of Spells and Potions', 'medium', ['Binary Search', 'Sorting']],
            [162, 'Find Peak Element', 'medium', ['Binary Search']],
            [875, 'Koko Eating Bananas', 'medium', ['Binary Search']],
            [17, 'Letter Combinations of a Phone Number', 'medium', ['Backtracking']],
            [216, 'Combination Sum III', 'medium', ['Backtracking']],
            [746, 'Min Cost Climbing Stairs', 'easy', ['DP']],
            [62, 'Unique Paths', 'medium', ['DP', 'Math']],
            [1143, 'Longest Common Subsequence', 'medium', ['DP']],
            [714, 'Best Time to Buy and Sell Stock with Transaction Fee', 'medium', ['DP', 'Greedy']],
            [72, 'Edit Distance', 'medium', ['DP']],
            [1137, 'N-th Tribonacci Number', 'easy', ['DP', 'Math']],
            [198, 'House Robber', 'medium', ['DP']],
            [790, 'Domino and Tromino Tiling', 'medium', ['DP']],
            [338, 'Counting Bits', 'easy', ['Bit Manipulation', 'DP']],
            [136, 'Single Number', 'easy', ['Bit Manipulation']],
            [1318, 'Minimum Flips to Make a OR b Equal to c', 'medium', ['Bit Manipulation']],
            [208, 'Implement Trie Prefix Tree', 'medium', ['Trie']],
            [1268, 'Search Suggestions System', 'medium', ['Trie', 'Strings', 'Sorting']],
            [435, 'Non-overlapping Intervals', 'medium', ['Intervals', 'Greedy', 'Sorting']],
            [452, 'Minimum Number of Arrows to Burst Balloons', 'medium', ['Intervals', 'Greedy', 'Sorting']],
            [739, 'Daily Temperatures', 'medium', ['Stack', 'Monotonic Stack']],
            [901, 'Online Stock Span', 'medium', ['Stack', 'Monotonic Stack']]
        ]
    },

    blind75: {
        name: 'Blind 75',
        desc: 'The essential 75 problems every candidate should master.',
        icon: '🔥',
        problems: [
            [1, 'Two Sum', 'easy', ['Arrays', 'Hash Map']],
            [121, 'Best Time to Buy and Sell Stock', 'easy', ['Arrays']],
            [217, 'Contains Duplicate', 'easy', ['Arrays']],
            [238, 'Product of Array Except Self', 'medium', ['Arrays']],
            [53, 'Maximum Subarray', 'medium', ['Arrays', 'DP']],
            [152, 'Maximum Product Subarray', 'medium', ['Arrays', 'DP']],
            [153, 'Find Minimum in Rotated Sorted Array', 'medium', ['Arrays', 'Binary Search']],
            [33, 'Search in Rotated Sorted Array', 'medium', ['Arrays', 'Binary Search']],
            [15, '3Sum', 'medium', ['Arrays', 'Two Pointers']],
            [11, 'Container With Most Water', 'medium', ['Arrays', 'Two Pointers']],
            [371, 'Sum of Two Integers', 'medium', ['Bit Manipulation']],
            [191, 'Number of 1 Bits', 'easy', ['Bit Manipulation']],
            [338, 'Counting Bits', 'easy', ['Bit Manipulation', 'DP']],
            [268, 'Missing Number', 'easy', ['Bit Manipulation']],
            [190, 'Reverse Bits', 'easy', ['Bit Manipulation']],
            [70, 'Climbing Stairs', 'easy', ['DP']],
            [322, 'Coin Change', 'medium', ['DP']],
            [300, 'Longest Increasing Subsequence', 'medium', ['DP']],
            [1143, 'Longest Common Subsequence', 'medium', ['DP']],
            [139, 'Word Break', 'medium', ['DP']],
            [377, 'Combination Sum IV', 'medium', ['DP']],
            [198, 'House Robber', 'medium', ['DP']],
            [213, 'House Robber II', 'medium', ['DP']],
            [91, 'Decode Ways', 'medium', ['DP']],
            [62, 'Unique Paths', 'medium', ['DP']],
            [55, 'Jump Game', 'medium', ['DP', 'Greedy']],
            [133, 'Clone Graph', 'medium', ['Graphs']],
            [207, 'Course Schedule', 'medium', ['Graphs']],
            [417, 'Pacific Atlantic Water Flow', 'medium', ['Graphs', 'DFS']],
            [200, 'Number of Islands', 'medium', ['Graphs', 'DFS']],
            [128, 'Longest Consecutive Sequence', 'medium', ['Arrays', 'Hash Map']],
            [269, 'Alien Dictionary', 'hard', ['Graphs', 'Topological Sort']],
            [261, 'Graph Valid Tree', 'medium', ['Graphs', 'Union Find']],
            [323, 'Number of Connected Components', 'medium', ['Graphs', 'Union Find']],
            [57, 'Insert Interval', 'medium', ['Intervals']],
            [56, 'Merge Intervals', 'medium', ['Intervals']],
            [435, 'Non-overlapping Intervals', 'medium', ['Intervals']],
            [252, 'Meeting Rooms', 'easy', ['Intervals']],
            [253, 'Meeting Rooms II', 'medium', ['Intervals']],
            [206, 'Reverse Linked List', 'easy', ['Linked List']],
            [141, 'Linked List Cycle', 'easy', ['Linked List']],
            [21, 'Merge Two Sorted Lists', 'easy', ['Linked List']],
            [23, 'Merge k Sorted Lists', 'hard', ['Linked List', 'Heap']],
            [19, 'Remove Nth Node From End', 'medium', ['Linked List']],
            [143, 'Reorder List', 'medium', ['Linked List']],
            [73, 'Set Matrix Zeroes', 'medium', ['Matrix']],
            [54, 'Spiral Matrix', 'medium', ['Matrix']],
            [48, 'Rotate Image', 'medium', ['Matrix']],
            [79, 'Word Search', 'medium', ['Matrix', 'Backtracking']],
            [3, 'Longest Substring Without Repeating', 'medium', ['Strings', 'Sliding Window']],
            [424, 'Longest Repeating Character Replacement', 'medium', ['Strings', 'Sliding Window']],
            [76, 'Minimum Window Substring', 'hard', ['Strings', 'Sliding Window']],
            [242, 'Valid Anagram', 'easy', ['Strings']],
            [49, 'Group Anagrams', 'medium', ['Strings', 'Hash Map']],
            [20, 'Valid Parentheses', 'easy', ['Strings', 'Stack']],
            [125, 'Valid Palindrome', 'easy', ['Strings', 'Two Pointers']],
            [5, 'Longest Palindromic Substring', 'medium', ['Strings', 'DP']],
            [647, 'Palindromic Substrings', 'medium', ['Strings', 'DP']],
            [271, 'Encode and Decode Strings', 'medium', ['Strings']],
            [104, 'Maximum Depth of Binary Tree', 'easy', ['Trees']],
            [100, 'Same Tree', 'easy', ['Trees']],
            [226, 'Invert Binary Tree', 'easy', ['Trees']],
            [124, 'Binary Tree Maximum Path Sum', 'hard', ['Trees', 'DFS']],
            [102, 'Binary Tree Level Order Traversal', 'medium', ['Trees', 'BFS']],
            [297, 'Serialize and Deserialize Binary Tree', 'hard', ['Trees']],
            [572, 'Subtree of Another Tree', 'easy', ['Trees']],
            [105, 'Construct Binary Tree from Preorder and Inorder', 'medium', ['Trees']],
            [98, 'Validate Binary Search Tree', 'medium', ['Trees', 'BST']],
            [230, 'Kth Smallest Element in BST', 'medium', ['Trees', 'BST']],
            [235, 'Lowest Common Ancestor of BST', 'medium', ['Trees', 'BST']],
            [208, 'Implement Trie', 'medium', ['Trie']],
            [211, 'Design Add and Search Words', 'medium', ['Trie']],
            [212, 'Word Search II', 'hard', ['Trie', 'Backtracking']],
            [347, 'Top K Frequent Elements', 'medium', ['Heap', 'Hash Map']],
            [295, 'Find Median from Data Stream', 'hard', ['Heap']]
        ]
    },

    neetcode150: {
        name: 'NeetCode 150',
        desc: 'Expanded curated list — 150 problems covering all major patterns.',
        icon: '📋',
        problems: [
            [217, 'Contains Duplicate', 'easy', ['Arrays']],
            [242, 'Valid Anagram', 'easy', ['Arrays']],
            [1, 'Two Sum', 'easy', ['Arrays', 'Hash Map']],
            [49, 'Group Anagrams', 'medium', ['Arrays', 'Hash Map']],
            [347, 'Top K Frequent Elements', 'medium', ['Heap']],
            [238, 'Product of Array Except Self', 'medium', ['Arrays']],
            [36, 'Valid Sudoku', 'medium', ['Arrays', 'Matrix']],
            [128, 'Longest Consecutive Sequence', 'medium', ['Arrays', 'Hash Map']],
            [125, 'Valid Palindrome', 'easy', ['Two Pointers']],
            [167, 'Two Sum II', 'medium', ['Two Pointers']],
            [15, '3Sum', 'medium', ['Two Pointers']],
            [11, 'Container With Most Water', 'medium', ['Two Pointers']],
            [42, 'Trapping Rain Water', 'hard', ['Two Pointers', 'Stack']],
            [121, 'Best Time to Buy and Sell Stock', 'easy', ['Sliding Window']],
            [3, 'Longest Substring Without Repeating', 'medium', ['Sliding Window']],
            [424, 'Longest Repeating Character Replacement', 'medium', ['Sliding Window']],
            [567, 'Permutation in String', 'medium', ['Sliding Window']],
            [76, 'Minimum Window Substring', 'hard', ['Sliding Window']],
            [239, 'Sliding Window Maximum', 'hard', ['Sliding Window', 'Deque']],
            [20, 'Valid Parentheses', 'easy', ['Stack']],
            [155, 'Min Stack', 'medium', ['Stack']],
            [150, 'Evaluate Reverse Polish Notation', 'medium', ['Stack']],
            [22, 'Generate Parentheses', 'medium', ['Stack', 'Backtracking']],
            [739, 'Daily Temperatures', 'medium', ['Stack']],
            [853, 'Car Fleet', 'medium', ['Stack']],
            [84, 'Largest Rectangle in Histogram', 'hard', ['Stack']],
            [704, 'Binary Search', 'easy', ['Binary Search']],
            [74, 'Search a 2D Matrix', 'medium', ['Binary Search']],
            [875, 'Koko Eating Bananas', 'medium', ['Binary Search']],
            [153, 'Find Min in Rotated Sorted Array', 'medium', ['Binary Search']],
            [33, 'Search in Rotated Sorted Array', 'medium', ['Binary Search']],
            [981, 'Time Based Key-Value Store', 'medium', ['Binary Search']],
            [4, 'Median of Two Sorted Arrays', 'hard', ['Binary Search']],
            [206, 'Reverse Linked List', 'easy', ['Linked List']],
            [21, 'Merge Two Sorted Lists', 'easy', ['Linked List']],
            [143, 'Reorder List', 'medium', ['Linked List']],
            [19, 'Remove Nth Node From End', 'medium', ['Linked List']],
            [138, 'Copy List with Random Pointer', 'medium', ['Linked List']],
            [2, 'Add Two Numbers', 'medium', ['Linked List']],
            [141, 'Linked List Cycle', 'easy', ['Linked List']],
            [287, 'Find the Duplicate Number', 'medium', ['Linked List']],
            [146, 'LRU Cache', 'medium', ['Linked List', 'Hash Map']],
            [23, 'Merge k Sorted Lists', 'hard', ['Linked List', 'Heap']],
            [25, 'Reverse Nodes in k-Group', 'hard', ['Linked List']],
            [226, 'Invert Binary Tree', 'easy', ['Trees']],
            [104, 'Maximum Depth of Binary Tree', 'easy', ['Trees']],
            [543, 'Diameter of Binary Tree', 'easy', ['Trees']],
            [110, 'Balanced Binary Tree', 'easy', ['Trees']],
            [100, 'Same Tree', 'easy', ['Trees']],
            [572, 'Subtree of Another Tree', 'easy', ['Trees']],
            [235, 'Lowest Common Ancestor of BST', 'medium', ['Trees', 'BST']],
            [102, 'Binary Tree Level Order Traversal', 'medium', ['Trees', 'BFS']],
            [199, 'Binary Tree Right Side View', 'medium', ['Trees', 'BFS']],
            [1448, 'Count Good Nodes in Binary Tree', 'medium', ['Trees', 'DFS']],
            [98, 'Validate BST', 'medium', ['Trees', 'BST']],
            [230, 'Kth Smallest Element in BST', 'medium', ['Trees', 'BST']],
            [105, 'Construct Tree from Preorder/Inorder', 'medium', ['Trees']],
            [124, 'Binary Tree Max Path Sum', 'hard', ['Trees', 'DFS']],
            [297, 'Serialize and Deserialize Binary Tree', 'hard', ['Trees']],
            [208, 'Implement Trie', 'medium', ['Trie']],
            [211, 'Add and Search Words', 'medium', ['Trie']],
            [212, 'Word Search II', 'hard', ['Trie', 'Backtracking']],
            [355, 'Design Twitter', 'medium', ['Heap', 'OOP']],
            [703, 'Kth Largest Element in Stream', 'easy', ['Heap']],
            [1046, 'Last Stone Weight', 'easy', ['Heap']],
            [973, 'K Closest Points to Origin', 'medium', ['Heap']],
            [215, 'Kth Largest Element in Array', 'medium', ['Heap']],
            [621, 'Task Scheduler', 'medium', ['Heap', 'Greedy']],
            [295, 'Find Median from Data Stream', 'hard', ['Heap']],
            [78, 'Subsets', 'medium', ['Backtracking']],
            [39, 'Combination Sum', 'medium', ['Backtracking']],
            [46, 'Permutations', 'medium', ['Backtracking']],
            [90, 'Subsets II', 'medium', ['Backtracking']],
            [40, 'Combination Sum II', 'medium', ['Backtracking']],
            [79, 'Word Search', 'medium', ['Backtracking', 'Matrix']],
            [131, 'Palindrome Partitioning', 'medium', ['Backtracking']],
            [17, 'Letter Combinations of Phone Number', 'medium', ['Backtracking']],
            [51, 'N-Queens', 'hard', ['Backtracking']],
            [200, 'Number of Islands', 'medium', ['Graphs', 'DFS']],
            [133, 'Clone Graph', 'medium', ['Graphs']],
            [695, 'Max Area of Island', 'medium', ['Graphs', 'DFS']],
            [417, 'Pacific Atlantic Water Flow', 'medium', ['Graphs', 'DFS']],
            [130, 'Surrounded Regions', 'medium', ['Graphs', 'DFS']],
            [994, 'Rotting Oranges', 'medium', ['Graphs', 'BFS']],
            [286, 'Walls and Gates', 'medium', ['Graphs', 'BFS']],
            [207, 'Course Schedule', 'medium', ['Graphs']],
            [210, 'Course Schedule II', 'medium', ['Graphs']],
            [684, 'Redundant Connection', 'medium', ['Graphs', 'Union Find']],
            [323, 'Number of Connected Components', 'medium', ['Graphs', 'Union Find']],
            [261, 'Graph Valid Tree', 'medium', ['Graphs', 'Union Find']],
            [127, 'Word Ladder', 'hard', ['Graphs', 'BFS']],
            [70, 'Climbing Stairs', 'easy', ['DP']],
            [746, 'Min Cost Climbing Stairs', 'easy', ['DP']],
            [198, 'House Robber', 'medium', ['DP']],
            [213, 'House Robber II', 'medium', ['DP']],
            [5, 'Longest Palindromic Substring', 'medium', ['DP']],
            [647, 'Palindromic Substrings', 'medium', ['DP']],
            [91, 'Decode Ways', 'medium', ['DP']],
            [322, 'Coin Change', 'medium', ['DP']],
            [152, 'Maximum Product Subarray', 'medium', ['DP']],
            [139, 'Word Break', 'medium', ['DP']],
            [300, 'Longest Increasing Subsequence', 'medium', ['DP']],
            [416, 'Partition Equal Subset Sum', 'medium', ['DP']],
            [62, 'Unique Paths', 'medium', ['DP']],
            [1143, 'Longest Common Subsequence', 'medium', ['DP']],
            [309, 'Best Time Buy Sell Stock Cooldown', 'medium', ['DP']],
            [518, 'Coin Change II', 'medium', ['DP']],
            [494, 'Target Sum', 'medium', ['DP']],
            [97, 'Interleaving String', 'medium', ['DP']],
            [329, 'Longest Increasing Path in Matrix', 'hard', ['DP', 'DFS']],
            [115, 'Distinct Subsequences', 'hard', ['DP']],
            [72, 'Edit Distance', 'medium', ['DP']],
            [312, 'Burst Balloons', 'hard', ['DP']],
            [10, 'Regular Expression Matching', 'hard', ['DP']],
            [56, 'Merge Intervals', 'medium', ['Intervals']],
            [57, 'Insert Interval', 'medium', ['Intervals']],
            [435, 'Non-overlapping Intervals', 'medium', ['Intervals', 'Greedy']],
            [252, 'Meeting Rooms', 'easy', ['Intervals']],
            [253, 'Meeting Rooms II', 'medium', ['Intervals']],
            [1851, 'Min Interval to Include Each Query', 'hard', ['Intervals']],
            [48, 'Rotate Image', 'medium', ['Math', 'Matrix']],
            [54, 'Spiral Matrix', 'medium', ['Matrix']],
            [73, 'Set Matrix Zeroes', 'medium', ['Matrix']],
            [202, 'Happy Number', 'easy', ['Math']],
            [66, 'Plus One', 'easy', ['Math']],
            [50, 'Pow(x,n)', 'medium', ['Math']],
            [43, 'Multiply Strings', 'medium', ['Math']],
            [2013, 'Detect Squares', 'medium', ['Math']],
            [371, 'Sum of Two Integers', 'medium', ['Bit Manipulation']],
            [191, 'Number of 1 Bits', 'easy', ['Bit Manipulation']],
            [338, 'Counting Bits', 'easy', ['Bit Manipulation']],
            [190, 'Reverse Bits', 'easy', ['Bit Manipulation']],
            [268, 'Missing Number', 'easy', ['Bit Manipulation']],
            [7, 'Reverse Integer', 'medium', ['Math']],
            [53, 'Maximum Subarray', 'medium', ['Greedy']],
            [55, 'Jump Game', 'medium', ['Greedy']],
            [45, 'Jump Game II', 'medium', ['Greedy']],
            [134, 'Gas Station', 'medium', ['Greedy']],
            [846, 'Hand of Straights', 'medium', ['Greedy']],
            [1899, 'Merge Triplets to Form Target', 'medium', ['Greedy']],
            [763, 'Partition Labels', 'medium', ['Greedy']],
            [678, 'Valid Parenthesis String', 'medium', ['Greedy']],
            [332, 'Reconstruct Itinerary', 'hard', ['Graphs']],
            [1584, 'Min Cost to Connect All Points', 'medium', ['Graphs', 'MST']],
            [743, 'Network Delay Time', 'medium', ['Graphs', 'Dijkstra']],
            [787, 'Cheapest Flights Within K Stops', 'medium', ['Graphs', 'Dijkstra']],
            [269, 'Alien Dictionary', 'hard', ['Graphs', 'Topological Sort']]
        ]
    },

    striver60: {
        name: 'Striver SDE Sheet',
        desc: '60 key problems for product-based company interviews.',
        icon: '⚡',
        problems: [
            [73, 'Set Matrix Zeroes', 'medium', ['Matrix']],
            [118, 'Pascals Triangle', 'easy', ['Arrays']],
            [31, 'Next Permutation', 'medium', ['Arrays']],
            [53, 'Maximum Subarray', 'medium', ['Arrays', 'DP']],
            [75, 'Sort Colors', 'medium', ['Arrays', 'Two Pointers']],
            [121, 'Best Time to Buy and Sell Stock', 'easy', ['Arrays']],
            [48, 'Rotate Image', 'medium', ['Matrix']],
            [56, 'Merge Intervals', 'medium', ['Intervals']],
            [88, 'Merge Sorted Array', 'easy', ['Arrays']],
            [287, 'Find the Duplicate Number', 'medium', ['Arrays']],
            [26, 'Remove Duplicates from Sorted Array', 'easy', ['Arrays']],
            [1, 'Two Sum', 'easy', ['Arrays', 'Hash Map']],
            [15, '3Sum', 'medium', ['Two Pointers']],
            [18, '4Sum', 'medium', ['Two Pointers']],
            [128, 'Longest Consecutive Sequence', 'medium', ['Hash Map']],
            [206, 'Reverse Linked List', 'easy', ['Linked List']],
            [876, 'Middle of the Linked List', 'easy', ['Linked List']],
            [21, 'Merge Two Sorted Lists', 'easy', ['Linked List']],
            [19, 'Remove Nth Node From End', 'medium', ['Linked List']],
            [2, 'Add Two Numbers', 'medium', ['Linked List']],
            [141, 'Linked List Cycle', 'easy', ['Linked List']],
            [142, 'Linked List Cycle II', 'medium', ['Linked List']],
            [160, 'Intersection of Two Linked Lists', 'easy', ['Linked List']],
            [234, 'Palindrome Linked List', 'easy', ['Linked List']],
            [25, 'Reverse Nodes in k-Group', 'hard', ['Linked List']],
            [61, 'Rotate List', 'medium', ['Linked List']],
            [62, 'Unique Paths', 'medium', ['DP']],
            [50, 'Pow(x,n)', 'medium', ['Math']],
            [169, 'Majority Element', 'easy', ['Arrays']],
            [229, 'Majority Element II', 'medium', ['Arrays']],
            [74, 'Search a 2D Matrix', 'medium', ['Binary Search']],
            [34, 'First and Last Position', 'medium', ['Binary Search']],
            [33, 'Search in Rotated Sorted Array', 'medium', ['Binary Search']],
            [20, 'Valid Parentheses', 'easy', ['Stack']],
            [496, 'Next Greater Element I', 'easy', ['Stack']],
            [155, 'Min Stack', 'medium', ['Stack']],
            [84, 'Largest Rectangle in Histogram', 'hard', ['Stack']],
            [94, 'Binary Tree Inorder Traversal', 'easy', ['Trees']],
            [144, 'Binary Tree Preorder Traversal', 'easy', ['Trees']],
            [145, 'Binary Tree Postorder Traversal', 'easy', ['Trees']],
            [104, 'Maximum Depth of Binary Tree', 'easy', ['Trees']],
            [110, 'Balanced Binary Tree', 'easy', ['Trees']],
            [543, 'Diameter of Binary Tree', 'easy', ['Trees']],
            [124, 'Binary Tree Maximum Path Sum', 'hard', ['Trees', 'DFS']],
            [102, 'Binary Tree Level Order Traversal', 'medium', ['Trees', 'BFS']],
            [236, 'Lowest Common Ancestor', 'medium', ['Trees']],
            [101, 'Symmetric Tree', 'easy', ['Trees']],
            [226, 'Invert Binary Tree', 'easy', ['Trees']],
            [98, 'Validate BST', 'medium', ['Trees', 'BST']],
            [230, 'Kth Smallest Element in BST', 'medium', ['Trees', 'BST']],
            [78, 'Subsets', 'medium', ['Backtracking']],
            [46, 'Permutations', 'medium', ['Backtracking']],
            [39, 'Combination Sum', 'medium', ['Backtracking']],
            [200, 'Number of Islands', 'medium', ['Graphs', 'DFS']],
            [207, 'Course Schedule', 'medium', ['Graphs']],
            [210, 'Course Schedule II', 'medium', ['Graphs']],
            [733, 'Flood Fill', 'easy', ['Graphs', 'DFS']],
            [785, 'Is Graph Bipartite', 'medium', ['Graphs']],
            [322, 'Coin Change', 'medium', ['DP']],
            [300, 'Longest Increasing Subsequence', 'medium', ['DP']]
        ]
    },

    google50: {
        name: 'Google Top 50',
        desc: 'Most frequently asked at Google interviews.',
        icon: '🏢',
        problems: [
            [1, 'Two Sum', 'easy', ['Arrays', 'Hash Map']],
            [4, 'Median of Two Sorted Arrays', 'hard', ['Binary Search']],
            [5, 'Longest Palindromic Substring', 'medium', ['DP']],
            [11, 'Container With Most Water', 'medium', ['Two Pointers']],
            [15, '3Sum', 'medium', ['Two Pointers']],
            [20, 'Valid Parentheses', 'easy', ['Stack']],
            [22, 'Generate Parentheses', 'medium', ['Backtracking']],
            [33, 'Search in Rotated Sorted Array', 'medium', ['Binary Search']],
            [42, 'Trapping Rain Water', 'hard', ['Two Pointers']],
            [46, 'Permutations', 'medium', ['Backtracking']],
            [48, 'Rotate Image', 'medium', ['Matrix']],
            [49, 'Group Anagrams', 'medium', ['Hash Map']],
            [53, 'Maximum Subarray', 'medium', ['DP']],
            [56, 'Merge Intervals', 'medium', ['Intervals']],
            [76, 'Minimum Window Substring', 'hard', ['Sliding Window']],
            [98, 'Validate BST', 'medium', ['Trees']],
            [121, 'Best Time to Buy and Sell Stock', 'easy', ['Arrays']],
            [127, 'Word Ladder', 'hard', ['Graphs', 'BFS']],
            [133, 'Clone Graph', 'medium', ['Graphs']],
            [139, 'Word Break', 'medium', ['DP']],
            [146, 'LRU Cache', 'medium', ['Design']],
            [153, 'Find Min in Rotated Sorted Array', 'medium', ['Binary Search']],
            [155, 'Min Stack', 'medium', ['Stack']],
            [200, 'Number of Islands', 'medium', ['Graphs']],
            [206, 'Reverse Linked List', 'easy', ['Linked List']],
            [207, 'Course Schedule', 'medium', ['Graphs']],
            [208, 'Implement Trie', 'medium', ['Trie']],
            [215, 'Kth Largest Element', 'medium', ['Heap']],
            [226, 'Invert Binary Tree', 'easy', ['Trees']],
            [230, 'Kth Smallest Element in BST', 'medium', ['Trees']],
            [236, 'Lowest Common Ancestor', 'medium', ['Trees']],
            [238, 'Product of Array Except Self', 'medium', ['Arrays']],
            [239, 'Sliding Window Maximum', 'hard', ['Deque']],
            [253, 'Meeting Rooms II', 'medium', ['Intervals']],
            [269, 'Alien Dictionary', 'hard', ['Topological Sort']],
            [283, 'Move Zeroes', 'easy', ['Arrays']],
            [295, 'Find Median from Data Stream', 'hard', ['Heap']],
            [297, 'Serialize and Deserialize Binary Tree', 'hard', ['Trees']],
            [300, 'Longest Increasing Subsequence', 'medium', ['DP']],
            [322, 'Coin Change', 'medium', ['DP']],
            [329, 'Longest Increasing Path in Matrix', 'hard', ['DFS']],
            [347, 'Top K Frequent Elements', 'medium', ['Heap']],
            [394, 'Decode String', 'medium', ['Stack']],
            [417, 'Pacific Atlantic Water Flow', 'medium', ['DFS']],
            [543, 'Diameter of Binary Tree', 'easy', ['Trees']],
            [560, 'Subarray Sum Equals K', 'medium', ['Hash Map']],
            [621, 'Task Scheduler', 'medium', ['Greedy']],
            [739, 'Daily Temperatures', 'medium', ['Stack']],
            [973, 'K Closest Points to Origin', 'medium', ['Heap']],
            [994, 'Rotting Oranges', 'medium', ['BFS']]
        ]
    },

    amazon50: {
        name: 'Amazon Top 50',
        desc: 'Most frequently asked at Amazon interviews.',
        icon: '📦',
        problems: [
            [1, 'Two Sum', 'easy', ['Arrays', 'Hash Map']],
            [2, 'Add Two Numbers', 'medium', ['Linked List']],
            [3, 'Longest Substring Without Repeating', 'medium', ['Sliding Window']],
            [5, 'Longest Palindromic Substring', 'medium', ['DP']],
            [15, '3Sum', 'medium', ['Two Pointers']],
            [17, 'Letter Combinations of Phone Number', 'medium', ['Backtracking']],
            [20, 'Valid Parentheses', 'easy', ['Stack']],
            [21, 'Merge Two Sorted Lists', 'easy', ['Linked List']],
            [23, 'Merge k Sorted Lists', 'hard', ['Heap']],
            [42, 'Trapping Rain Water', 'hard', ['Two Pointers']],
            [49, 'Group Anagrams', 'medium', ['Hash Map']],
            [53, 'Maximum Subarray', 'medium', ['DP']],
            [56, 'Merge Intervals', 'medium', ['Intervals']],
            [73, 'Set Matrix Zeroes', 'medium', ['Matrix']],
            [79, 'Word Search', 'medium', ['Backtracking']],
            [98, 'Validate BST', 'medium', ['Trees']],
            [102, 'Binary Tree Level Order Traversal', 'medium', ['Trees']],
            [121, 'Best Time to Buy and Sell Stock', 'easy', ['Arrays']],
            [126, 'Word Ladder II', 'hard', ['BFS']],
            [127, 'Word Ladder', 'hard', ['BFS']],
            [138, 'Copy List with Random Pointer', 'medium', ['Linked List']],
            [139, 'Word Break', 'medium', ['DP']],
            [146, 'LRU Cache', 'medium', ['Design']],
            [200, 'Number of Islands', 'medium', ['Graphs']],
            [206, 'Reverse Linked List', 'easy', ['Linked List']],
            [207, 'Course Schedule', 'medium', ['Graphs']],
            [210, 'Course Schedule II', 'medium', ['Graphs']],
            [212, 'Word Search II', 'hard', ['Trie']],
            [215, 'Kth Largest Element', 'medium', ['Heap']],
            [230, 'Kth Smallest Element in BST', 'medium', ['Trees']],
            [235, 'Lowest Common Ancestor of BST', 'medium', ['Trees']],
            [236, 'Lowest Common Ancestor', 'medium', ['Trees']],
            [238, 'Product of Array Except Self', 'medium', ['Arrays']],
            [239, 'Sliding Window Maximum', 'hard', ['Deque']],
            [253, 'Meeting Rooms II', 'medium', ['Intervals']],
            [273, 'Integer to English Words', 'hard', ['Math']],
            [295, 'Find Median from Data Stream', 'hard', ['Heap']],
            [297, 'Serialize and Deserialize Binary Tree', 'hard', ['Trees']],
            [322, 'Coin Change', 'medium', ['DP']],
            [347, 'Top K Frequent Elements', 'medium', ['Heap']],
            [380, 'Insert Delete GetRandom O(1)', 'medium', ['Design']],
            [394, 'Decode String', 'medium', ['Stack']],
            [572, 'Subtree of Another Tree', 'easy', ['Trees']],
            [588, 'Design In-Memory File System', 'hard', ['Design']],
            [692, 'Top K Frequent Words', 'medium', ['Heap']],
            [706, 'Design HashMap', 'easy', ['Design']],
            [819, 'Most Common Word', 'easy', ['Hash Map']],
            [937, 'Reorder Data in Log Files', 'medium', ['Sorting']],
            [973, 'K Closest Points to Origin', 'medium', ['Heap']],
            [994, 'Rotting Oranges', 'medium', ['BFS']]
        ]
    },

    meta50: {
        name: 'Meta Top 50',
        desc: 'Most frequently asked at Meta/Facebook interviews.',
        icon: '🔵',
        problems: [
            [1, 'Two Sum', 'easy', ['Arrays', 'Hash Map']],
            [3, 'Longest Substring Without Repeating', 'medium', ['Sliding Window']],
            [4, 'Median of Two Sorted Arrays', 'hard', ['Binary Search']],
            [15, '3Sum', 'medium', ['Two Pointers']],
            [20, 'Valid Parentheses', 'easy', ['Stack']],
            [21, 'Merge Two Sorted Lists', 'easy', ['Linked List']],
            [23, 'Merge k Sorted Lists', 'hard', ['Heap']],
            [33, 'Search in Rotated Sorted Array', 'medium', ['Binary Search']],
            [50, 'Pow(x,n)', 'medium', ['Math']],
            [56, 'Merge Intervals', 'medium', ['Intervals']],
            [67, 'Add Binary', 'easy', ['Math']],
            [76, 'Minimum Window Substring', 'hard', ['Sliding Window']],
            [88, 'Merge Sorted Array', 'easy', ['Arrays']],
            [98, 'Validate BST', 'medium', ['Trees']],
            [102, 'Binary Tree Level Order Traversal', 'medium', ['Trees']],
            [121, 'Best Time to Buy and Sell Stock', 'easy', ['Arrays']],
            [124, 'Binary Tree Max Path Sum', 'hard', ['Trees']],
            [125, 'Valid Palindrome', 'easy', ['Two Pointers']],
            [133, 'Clone Graph', 'medium', ['Graphs']],
            [138, 'Copy List with Random Pointer', 'medium', ['Linked List']],
            [139, 'Word Break', 'medium', ['DP']],
            [146, 'LRU Cache', 'medium', ['Design']],
            [199, 'Binary Tree Right Side View', 'medium', ['Trees']],
            [200, 'Number of Islands', 'medium', ['Graphs']],
            [206, 'Reverse Linked List', 'easy', ['Linked List']],
            [207, 'Course Schedule', 'medium', ['Graphs']],
            [215, 'Kth Largest Element', 'medium', ['Heap']],
            [236, 'Lowest Common Ancestor', 'medium', ['Trees']],
            [238, 'Product of Array Except Self', 'medium', ['Arrays']],
            [253, 'Meeting Rooms II', 'medium', ['Intervals']],
            [269, 'Alien Dictionary', 'hard', ['Topological Sort']],
            [273, 'Integer to English Words', 'hard', ['Math']],
            [278, 'First Bad Version', 'easy', ['Binary Search']],
            [282, 'Expression Add Operators', 'hard', ['Backtracking']],
            [297, 'Serialize and Deserialize Binary Tree', 'hard', ['Trees']],
            [301, 'Remove Invalid Parentheses', 'hard', ['Backtracking']],
            [314, 'Binary Tree Vertical Order', 'medium', ['Trees', 'BFS']],
            [339, 'Nested List Weight Sum', 'medium', ['DFS']],
            [347, 'Top K Frequent Elements', 'medium', ['Heap']],
            [380, 'Insert Delete GetRandom O(1)', 'medium', ['Design']],
            [426, 'Convert BST to Sorted Doubly LL', 'medium', ['Trees']],
            [528, 'Random Pick with Weight', 'medium', ['Binary Search']],
            [543, 'Diameter of Binary Tree', 'easy', ['Trees']],
            [560, 'Subarray Sum Equals K', 'medium', ['Hash Map']],
            [621, 'Task Scheduler', 'medium', ['Greedy']],
            [680, 'Valid Palindrome II', 'easy', ['Two Pointers']],
            [721, 'Accounts Merge', 'medium', ['Union Find']],
            [766, 'Toeplitz Matrix', 'easy', ['Matrix']],
            [973, 'K Closest Points to Origin', 'medium', ['Heap']],
            [986, 'Interval List Intersections', 'medium', ['Two Pointers']]
        ]
    }
};

// Helper to expand compact format into full problem objects
function expandSheet(sheetKey) {
    const sheet = SHEETS[sheetKey];
    if (!sheet) return [];
    return sheet.problems.map(p => ({
        leetcodeId: p[0],
        title: p[1],
        difficulty: p[2],
        tags: p[3],
        url: `https://leetcode.com/problems/${p[1].toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '')}/`
    }));
}
